In [1]:
personas = {
    "nombre" : ["Juan","Jaime","Raul"],
    "apellido" : ["Fernández","Fernández","Martínez"],
    "email" : ["JR@gmail.com","JF@gmail.com","RM@gmail.com"]
}

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame(personas)

In [4]:
df

  nombre   apellido         email
0   Juan  Fernández  JR@gmail.com
1  Jaime  Fernández  JF@gmail.com
2   Raul   Martínez  RM@gmail.com

In [5]:
filtro = (df["nombre"] == "Jaime") & (df['apellido'] == 'Fernández')

In [6]:
df.loc[filtro,'email'] #Nos permite seleccionar filas y columnas en una única operación

1    JF@gmail.com
Name: email, dtype: object

In [7]:
filtro_2 = (df["nombre"] == "Jaime") | (df["nombre"] == "Juan")

In [8]:
df.loc[filtro_2]

  nombre   apellido         email
0   Juan  Fernández  JR@gmail.com
1  Jaime  Fernández  JF@gmail.com

In [9]:
df.loc[~filtro_2] #Buscamos lo contrario a nuestro filtro

  nombre  apellido         email
2   Raul  Martínez  RM@gmail.com